### ISSUE TITLE
Add support for SetSpeedBased

### ISSUE THREAD

**Issue by DogeThis** [grofit/dotween-nodecanvas#3]
Should expose this useful parameter.

**Comment by DogeThis** [comment]
> SetSpeedBased(bool isSpeedBased = true)
> If isSpeedBased is TRUE sets the tween as speed based (the duration will represent the number of units/degrees the tween moves x second). NOTE: if you want your speed to be constant, also set the ease to Ease.Linear. 
> Has no effect if the tween has already started or is inside a Sequence.

```
transform.DOMoveX(4, 1).SetSpeedBased();
```

**Comment by grofit** [comment]
Add a pull request once you get it working and will merge in

**Comment by grofit** [comment]
Have merged in the pull request, will close this but feel free to add others or comment further on here if needed.

**Comment by armnotstrong** [comment]
Hi,

> If isSpeedBased is TRUE sets the tween as speed based (the duration will represent the number of units/degrees the tween moves x second).

Here x is 1 right? If I understand right, when set tween as speed based, the duration became a parameter which indicts how much units the tween changes per second?
